# Generated by Django 2.2 on 2020-06-09 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0005_auto_20170307_0657'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='profile_pic',
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='portfolio_pic',
            field=models.ImageField(blank=True, upload_to='profile_pics'),
        ),
    ]
